AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Quarry releases - static site serving download page and auto-update artifacts

Parameters:
  PublicRootDomain:
    Type: String
    Description: Public root domain for DNS (e.g. internal.invalid)

Resources:
  Website:
    Type: RQP::StaticSite
    Properties:
      Content: buildkite://content.zip
      PublicDomainRoot: !Ref PublicRootDomain
      Subdomain: !Sub "quarry${DNSFriendlySliceSuffix}"
      CustomErrorResponses:
        - ErrorCode: 404
          ResponseCode: 404
          ResponsePagePath: /index.html
      DefaultCacheBehavior:
        CachePolicyId: CachingDisabled
