AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Quarry desktop app release hosting - S3 + CloudFront for electron-updater

Resources:
  Website:
    Type: RQP::StaticSite
    Properties:
      Content: file://content.zip
