/**
 * Widget catalogue — a declarative, never-executable UI primitive set.
 *
 * The agent emits a TREE OF JSON from this fixed catalogue; the client renders
 * known node types with bound data. No HTML, no scripts, no remote URLs. That
 * is the entire safety argument: it replaces raw-HTML artifacts (an XSS and
 * data-egress hazard) with a rendering layer that can only ever draw from
 * primitives we control.
 *
 * Design ported from Burnbox's A2UI, which has
 * survived real use. Deliberately distinct from `lib/a2ui/` — that is
 * Anthropic's A2UI canvas type system for conversational artifacts; this is a
 * small dashboard-tile vocabulary with a hard validation boundary.
 *
 * `coerceNode` is the boundary: untrusted JSON in, a valid node or null out. It
 * never throws — it DROPS. A widget is generated by a model from data that may
 * itself be attacker-influenced, so prompt-injection-into-widget is a real
 * threat, not a theoretical one.
 */

export type WidgetTone = 'neutral' | 'success' | 'warn' | 'danger' | 'info';
export type WidgetTrend = 'up' | 'down' | 'neutral';
export type ChartKind = 'bar' | 'line' | 'area' | 'pie';

export interface ChartPoint {
  label: string;
  value: number;
}

export interface StatItem {
  label: string;
  value: string;
  delta?: string;
  state?: WidgetTrend;
}

export type WidgetNode =
  | { type: 'text'; text: string; variant?: 'body' | 'heading' | 'subheading' | 'caption' | 'label' }
  | { type: 'metric'; label: string; value: string; delta?: string; state?: WidgetTrend }
  | { type: 'statGrid'; items: StatItem[] }
  | { type: 'list'; items: Array<{ text: string; sub?: string; badge?: string }>; ordered?: boolean }
  | { type: 'table'; columns: string[]; rows: string[][] }
  | { type: 'keyValue'; rows: Array<{ key: string; value: string }> }
  | { type: 'badge'; text: string; tone?: WidgetTone }
  | { type: 'timeline'; items: Array<{ time?: string; title: string; sub?: string }> }
  | { type: 'progress'; value: number; label?: string }
  | { type: 'chart'; chart: ChartKind; points: ChartPoint[]; title?: string; unit?: string }
  | { type: 'divider' }
  | { type: 'image'; src: string; alt?: string }
  | { type: 'actionButton'; label: string; action: string; tone?: WidgetTone }
  | { type: 'section'; title?: string; children: WidgetNode[] }
  | { type: 'card'; title?: string; subtitle?: string; children: WidgetNode[] };

export type WidgetNodeType = WidgetNode['type'];

// ── Limits ────────────────────────────────────────────────────────────────
// A generated tile that nests 200 deep or carries 50k of text is either a bug
// or an attack; either way it must not reach the renderer.
export const MAX_DEPTH = 8;
export const MAX_CHILDREN = 60;
export const MAX_ITEMS = 200;
export const MAX_TEXT = 4_000;

const TONES: WidgetTone[] = ['neutral', 'success', 'warn', 'danger', 'info'];
const TRENDS: WidgetTrend[] = ['up', 'down', 'neutral'];
const CHART_KINDS: ChartKind[] = ['bar', 'line', 'area', 'pie'];

// ── Field coercion ────────────────────────────────────────────────────────

function str(value: unknown, max = MAX_TEXT): string | null {
  if (typeof value !== 'string') return null;
  return value.slice(0, max);
}

/** A required string that must be non-empty after trimming. */
function reqStr(value: unknown, max = MAX_TEXT): string | null {
  const s = str(value, max);
  return s && s.trim() ? s : null;
}

function optStr(value: unknown, max = MAX_TEXT): string | undefined {
  const s = str(value, max);
  return s ?? undefined;
}

function num(value: unknown): number | null {
  return typeof value === 'number' && Number.isFinite(value) ? value : null;
}

function oneOf<T extends string>(value: unknown, allowed: T[]): T | undefined {
  return typeof value === 'string' && (allowed as string[]).includes(value) ? (value as T) : undefined;
}

function arr(value: unknown, max = MAX_ITEMS): unknown[] {
  return Array.isArray(value) ? value.slice(0, max) : [];
}

function rec(value: unknown): Record<string, unknown> | null {
  return value && typeof value === 'object' && !Array.isArray(value)
    ? (value as Record<string, unknown>)
    : null;
}

// ── The boundary ──────────────────────────────────────────────────────────

/**
 * Validate an untrusted value into a WidgetNode, or null. Never throws.
 * Unknown node types, malformed fields and over-deep trees are dropped rather
 * than repaired — a half-understood tile is worse than a missing one.
 */
export function coerceNode(input: unknown, depth = 0): WidgetNode | null {
  if (depth > MAX_DEPTH) return null;
  const o = rec(input);
  if (!o) return null;
  const type = o.type;

  switch (type) {
    case 'text': {
      const text = str(o.text);
      if (text === null) return null;
      return {
        type: 'text',
        text,
        variant: oneOf(o.variant, ['body', 'heading', 'subheading', 'caption', 'label']),
      };
    }

    case 'metric': {
      const label = reqStr(o.label, 200);
      const value = str(o.value, 200);
      if (!label || value === null) return null;
      return {
        type: 'metric',
        label,
        value,
        delta: optStr(o.delta, 60),
        state: oneOf(o.state, TRENDS),
      };
    }

    case 'statGrid': {
      const items: StatItem[] = [];
      for (const raw of arr(o.items)) {
        const s = rec(raw);
        if (!s) continue;
        const label = reqStr(s.label, 200);
        const value = str(s.value, 200);
        if (!label || value === null) continue;
        items.push({ label, value, delta: optStr(s.delta, 60), state: oneOf(s.state, TRENDS) });
      }
      return items.length ? { type: 'statGrid', items } : null;
    }

    case 'list': {
      const items: Array<{ text: string; sub?: string; badge?: string }> = [];
      for (const raw of arr(o.items)) {
        const i = rec(raw);
        if (!i) continue;
        const text = reqStr(i.text);
        if (!text) continue;
        items.push({ text, sub: optStr(i.sub), badge: optStr(i.badge, 60) });
      }
      return items.length ? { type: 'list', items, ordered: o.ordered === true } : null;
    }

    case 'table': {
      const columns = arr(o.columns, 20)
        .map((c) => str(c, 120))
        .filter((c): c is string => c !== null);
      if (!columns.length) return null;
      const rows: string[][] = [];
      for (const raw of arr(o.rows)) {
        if (!Array.isArray(raw)) continue;
        // Normalise ragged rows to the column count so the renderer can't be
        // handed a row that overflows its header.
        const cells = raw.slice(0, columns.length).map((c) => str(c, 500) ?? '');
        while (cells.length < columns.length) cells.push('');
        rows.push(cells);
      }
      return { type: 'table', columns, rows };
    }

    case 'keyValue': {
      const rows: Array<{ key: string; value: string }> = [];
      for (const raw of arr(o.rows)) {
        const r = rec(raw);
        if (!r) continue;
        const key = reqStr(r.key, 200);
        const value = str(r.value, 500);
        if (!key || value === null) continue;
        rows.push({ key, value });
      }
      return rows.length ? { type: 'keyValue', rows } : null;
    }

    case 'badge': {
      const text = reqStr(o.text, 120);
      return text ? { type: 'badge', text, tone: oneOf(o.tone, TONES) } : null;
    }

    case 'timeline': {
      const items: Array<{ time?: string; title: string; sub?: string }> = [];
      for (const raw of arr(o.items)) {
        const i = rec(raw);
        if (!i) continue;
        const title = reqStr(i.title);
        if (!title) continue;
        items.push({ time: optStr(i.time, 60), title, sub: optStr(i.sub) });
      }
      return items.length ? { type: 'timeline', items } : null;
    }

    case 'progress': {
      const value = num(o.value);
      if (value === null) return null;
      // Clamp rather than reject: a progress bar is self-evidently 0..100.
      return { type: 'progress', value: Math.max(0, Math.min(100, value)), label: optStr(o.label, 200) };
    }

    case 'chart': {
      const chart = oneOf(o.chart, CHART_KINDS);
      if (!chart) return null;
      const points: ChartPoint[] = [];
      for (const raw of arr(o.points)) {
        const p = rec(raw);
        if (!p) continue;
        const label = str(p.label, 120);
        const value = num(p.value);
        if (label === null || value === null) continue;
        // A negative slice is meaningless in a pie; bar/line/area allow them.
        if (chart === 'pie' && value < 0) continue;
        points.push({ label, value });
      }
      return points.length
        ? { type: 'chart', chart, points, title: optStr(o.title, 200), unit: optStr(o.unit, 40) }
        : null;
    }

    case 'divider':
      return { type: 'divider' };

    case 'image': {
      const src = str(o.src, 5_000_000);
      // Data URLs only. A remote src would leak the viewer's IP and an egress
      // signal from something the user was told is a declarative widget.
      if (src === null || !src.startsWith('data:image/')) return null;
      return { type: 'image', src, alt: optStr(o.alt, 200) };
    }

    case 'actionButton': {
      const label = reqStr(o.label, 120);
      /**
       * `action` is a NAME the host dispatches, never code and never a URL.
       * Note the absence of `:` — an earlier version allowed it for
       * namespacing, which let `javascript:x` through the filter. Harmless
       * while actions are only looked up in a handler map, but the entire
       * purpose of this layer is that its output cannot become dangerous if a
       * later renderer ever puts it somewhere URL-shaped. Dots namespace fine.
       */
      const action = reqStr(o.action, 120);
      if (!label || !action || !/^[\w.-]+$/.test(action)) return null;
      return { type: 'actionButton', label, action, tone: oneOf(o.tone, TONES) };
    }

    case 'section':
    case 'card': {
      const children: WidgetNode[] = [];
      for (const raw of arr(o.children, MAX_CHILDREN)) {
        const child = coerceNode(raw, depth + 1);
        if (child) children.push(child);
      }
      if (!children.length) return null;
      return type === 'section'
        ? { type: 'section', title: optStr(o.title, 200), children }
        : { type: 'card', title: optStr(o.title, 200), subtitle: optStr(o.subtitle, 300), children };
    }

    default:
      return null;
  }
}

/**
 * Public entry: parse and validate. Accepts a JSON string or a pre-parsed
 * value, so a stored blob and a live tool argument take the same path.
 */
export function parseWidget(input: unknown): WidgetNode | null {
  if (typeof input === 'string') {
    try {
      return coerceNode(JSON.parse(input));
    } catch {
      return null;
    }
  }
  return coerceNode(input);
}
